@echo off
setlocal enabledelayedexpansion
title Ò»´ÎĞÔÃÜÂëÉú³ÉÆ÷

:: ===== 1. Çë½«ÄúµÄË½Ô¿ Base64 Õ³Ìùµ½ÏÂ·½µÈºÅÓÒ²à =====
set "PRIKEY_B64=PFJTQUtleVZhbHVlPjxNb2R1bHVzPnplUmYzZmFzU3pNa0l4VWtQMFJ4ZnJ2K25DcWc3Z2FsUGRtYzdpMW9vNldtVWovVVMzVlU0bmRlQnM2b2N3c3JHWUFBbHFkWTh6TFpNbDFpajg1S0ljZXFIZVNxNXhKdkh2NGlzRkdBdWMzeFRXR09PVTYzWHpZNnNaV2NyUld5SHZkNGtvb1MzTUZVM2F3ZlhKRXQzdDIzUjJQb2QxWENKZXl4ZE9YeUFiSHRoaEdXd0RVSVFtejFFMHBYNmlTdTB1S21Ca0ZockpoSEJ0Z0pWUStuV1NHSmozdXR0VGx4Z3F6UkpnSzcycEE1SzA3MlEyQklkUFNsY1hObmgxQ0ZmY21zQzhVMzgzT1VnYmlIRG40RXQ2b0NTa0NxSytZTjFXaW5JVU1xb3p1czJ2Rk1HZjNHVlVFWUFsVWdJdFJFdjFPQXQ4RW85elhaRzV3dG5WMHBzUT09PC9Nb2R1bHVzPjxFeHBvbmVudD5BUUFCPC9FeHBvbmVudD48UD44dEZiZU1tWWcwdEFudGRpOGliY1p1eXdycFV2dXFVNUFoY0pQclR0YUp5MG1GdXlmYlRXZ2NJbzl3bTdLTmtFTERJL3BSdWYzb1owVjBDcXdNMnhISzhySDlKbTMvM1pWcHlRaUFxRmg5LzZDUU5BQStDb3dYSW1lY1p4c2FzRkE3eFdPVHRPYnplNnJRNUZrSHp3VTl5QlNPNTRNNnk4UkRISkg2YnNCaHM9PC9QPjxRPjJSSFVYT25SL2xra0M4WERRRnNPVEUzdlZ1TXZHTXNRdjljNngvU1VjemYwWmZZc1dvZnVtdnU1SGxCYm9VSitxWmtJaGQ1STlhbG1mQndyRGZDWkFCNnNDN2VnbjU1ZmxYMU9rR0hiU0VQSmtzZzdKTFR5VUxJdFJ6cFl4b1B0U0NSakFzTWcvbzYwNWc4M0tzeVNkWmY1RzZ1M1lKNndFZlpheTIrZVBDTT08L1E+PERQPkFqZ2xwT0g2MGVCak05QjJLQTV3MzBQMGpYUHhucndaM0VvSG5Kb2N2V01KUjRjM0IyMGF0TTdvZnZHSTAyUEFaUU1FaitiRHZFM3dURWZjQjYwWm5GQ0JqV1huNk00eUtWZCsvcTlSN3g3OTh3MGpqYVdGQlZlY3dHb3U2ZGZOVU81c3YxTXFjVnZLQ2dEaVkrS3djNlBGVHJ4WFB1bXFRdGxOcEV0clJ0Yz08L0RQPjxEUT5ZeTM2VWRtajBRcjVwVWRleHZEVHY1bDhXYjdEcmhoYU5zMG9WbVF4ejlNcEg4MHl4c3FGQXRzdzRlRGxmUERjM3JERmJDVDhRUUo5aVFkMXhKREIxNFFzSjg1bTNZZUhOTTVrTHlRSEJTV3ozQlVRc056Y09uS3VyWFREU3pETUljSStXdXk5RHBJMXBVZ2VkTGV6MDNiMG91ZjZpWEw0RDd6NER5dVlxUEU9PC9EUT48SW52ZXJzZVE+b2RNNk1qKzVtVHJ0cWFlWGU4RFlaTGNtQjlMNkNySUE1TFEzTTNLbDJWSEdyS2t3YU8xLzhPL3M4S04rZFp2Y1FVWXpjcUt4MnE2UjYwamg3SWhBZkozY3NhNHBjK24yTzRxU1ZEenFqMjkrR1UrcElabzM3NEoxSTE2Ri9nWlJYTWJ3a0lsVjNZb2haQ2dkZmJwRUh3cXYrTjM4Z1pXUk93dmp5bnloMUFJPTwvSW52ZXJzZVE+PEQ+UVBtVEwyOExER2hGUFRVTXpWS0NKcWFaUVJ0SzBoTVN6cVFBSEVJRVJiQ2UvbEhhWXozUjNlNGhwREJQaEk2L3VUcGw5U1Uyc3ZrWEJnZm1kTTk3SVpIckk2Zm9MeWZvSFhYQjZMYXYwdk1rOVhDVis0dlYzcHcwaFpwYmFWdnhiRWhZcXBZY1FjSlpUK05qdWtpdW15aUpFR1I5Rmp2Z0d5dkpETVVNVEhBVERWNEZHRTVKa1ZHNGZmUUdRaEFhVUFDbXZtQUMxeEZJZTJzcU5JMTQ3b05FSGR1Q21wTEx0WmJ0RVB1U3ZPSXl2RGtvcWpTaVlyUTFVZ0F5R1M2R2x4QUdjZXMzWTMvRmFaQjZrM3AzL3p5MGw4a29qZzkzd25oLzd6dG54YjdxZGN4L2VOTEJLOEQvR1dFWTRtUU9icDU1ZXZOWVlhWWtSMFZxYVRYaGlRPT08L0Q+PC9SU0FLZXlWYWx1ZT4="

:: ===== 2. ½«Ë½Ô¿Ğ´ÈëÁÙÊ±ÎÄ¼ş =====
set "TEMP_KEY_FILE=%TEMP%\prikey_%RANDOM%.tmp"
echo !PRIKEY_B64! > "!TEMP_KEY_FILE!"

:: ===== 3. ÊäÈë½âÃÜÃÜÔ¿ =====
set /p "encKey=ÇëÊäÈë½âÃÜÃÜÔ¿: "
if "%encKey%"=="" (
    echo ÃÜÔ¿²»ÄÜÎª¿Õ£¡
    del "!TEMP_KEY_FILE!" >nul 2>&1
    pause
    exit /b
)

:: ===== 4. µ÷ÓÃ PowerShell ½âÃÜ =====
powershell -ExecutionPolicy Bypass -Command ^
"$privateKeyXml = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String((Get-Content '%TEMP_KEY_FILE%'))); ^
$rsa = [System.Security.Cryptography.RSA]::Create(); $rsa.FromXmlString($privateKeyXml); ^
$encBytes = [Convert]::FromBase64String('%encKey%'); ^
try { ^
    $key = $rsa.Decrypt($encBytes, [System.Security.Cryptography.RSAEncryptionPadding]::OaepSHA1); ^
    Write-Host 'Ò»´ÎĞÔ½âÃÜÃÜÂë:' -NoNewline; ^
    Write-Host ([Convert]::ToBase64String($key)) ^
} catch { ^
    Write-Host '´íÎó£ºÃÜÔ¿ÎŞĞ§»òË½Ô¿²»Æ¥Åä' -ForegroundColor Red; ^
}"

:: ===== 5. É¾³ıÁÙÊ±ÎÄ¼ş =====
del "!TEMP_KEY_FILE!" >nul 2>&1
pause